export const CAMBIAR_SEARCHER = "CAMBIAR_SEARCHER";
export const CAMBIAR_SEARCHER_EXITO = "CAMBIAR_SEARCHER_EXITO";
export const CAMBIAR_SEARCHER_ERROR = "CAMBIAR_SEARCHER_ERROR";
export const OBTENER_DATOS = "OBTENER_DATOS";
export const OBTENER_DATOS_EXITO = "OBTENER_DATOS_EXITO";
export const OBTENER_DATOS_ERROR = "OBTENER_DATOS_ERROR";
